import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { AlertCircle, CheckCircle, Info } from "lucide-react";

interface AnalysisDisplayProps {
  analysis: string;
}

export const AnalysisDisplay = ({ analysis }: AnalysisDisplayProps) => {
  // Parse analysis text to extract key findings
  const sections = analysis.split("\n\n");

  return (
    <Card className="p-6">
      <div className="space-y-4">
        <div className="flex items-center justify-between">
          <h3 className="text-lg font-semibold">Analysis Report</h3>
          <Badge variant="outline" className="gap-1">
            <CheckCircle className="h-3 w-3" />
            Complete
          </Badge>
        </div>

        <div className="space-y-4">
          {sections.map((section, index) => {
            const isWarning = section.toLowerCase().includes("alert") || 
                            section.toLowerCase().includes("warning");
            const isInfo = section.toLowerCase().includes("note") ||
                          section.toLowerCase().includes("info");

            return (
              <div
                key={index}
                className={`p-4 rounded-lg border ${
                  isWarning
                    ? "bg-orange-50 dark:bg-orange-950 border-orange-200 dark:border-orange-800"
                    : isInfo
                    ? "bg-blue-50 dark:bg-blue-950 border-blue-200 dark:border-blue-800"
                    : "bg-muted border-muted"
                }`}
              >
                <div className="flex gap-3">
                  {isWarning && (
                    <AlertCircle className="h-5 w-5 text-orange-600 dark:text-orange-400 flex-shrink-0 mt-0.5" />
                  )}
                  {isInfo && (
                    <Info className="h-5 w-5 text-blue-600 dark:text-blue-400 flex-shrink-0 mt-0.5" />
                  )}
                  <p className="text-sm whitespace-pre-wrap">{section}</p>
                </div>
              </div>
            );
          })}
        </div>

        <div className="pt-4 border-t">
          <p className="text-xs text-muted-foreground">
            Analysis generated by AI. Use the chat below to ask specific questions.
          </p>
        </div>
      </div>
    </Card>
  );
};
